import { Category, Product } from "@/types";

export const mockCategories: Category[] = [
  { id: "1", name: "Electronics", slug: "electronics" },
  { id: "2", name: "Clothing", slug: "clothing" },
  { id: "3", name: "Home & Kitchen", slug: "home-kitchen" },
  { id: "4", name: "Sports", slug: "sports" },
  { id: "5", name: "Books", slug: "books" },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Wireless Headphones",
    description: "Premium noise-cancelling wireless headphones with 30-hour battery life",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
    category: "Electronics",
    stock: 45,
    rating: 4.5,
    isNew: true,
    onSale: false,
  },
  {
    id: "2",
    name: "Smart Watch",
    description: "Fitness tracker with heart rate monitor and GPS",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
    category: "Electronics",
    stock: 30,
    rating: 4.7,
    isNew: false,
    onSale: true,
  },
  {
    id: "3",
    name: "Cotton T-Shirt",
    description: "Comfortable 100% organic cotton t-shirt",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    category: "Clothing",
    stock: 120,
    rating: 4.3,
    isNew: false,
    onSale: false,
  },
  {
    id: "4",
    name: "Running Shoes",
    description: "Lightweight running shoes with advanced cushioning",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
    category: "Sports",
    stock: 60,
    rating: 4.6,
    isNew: true,
    onSale: false,
  },
  {
    id: "5",
    name: "Coffee Maker",
    description: "Programmable coffee maker with thermal carafe",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500",
    category: "Home & Kitchen",
    stock: 25,
    rating: 4.4,
    isNew: false,
    onSale: true,
  },
  {
    id: "6",
    name: "Yoga Mat",
    description: "Non-slip eco-friendly yoga mat with carrying strap",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500",
    category: "Sports",
    stock: 80,
    rating: 4.5,
    isNew: false,
    onSale: false,
  },
  {
    id: "7",
    name: "Bluetooth Speaker",
    description: "Portable waterproof speaker with 12-hour battery",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
    category: "Electronics",
    stock: 55,
    rating: 4.6,
    isNew: true,
    onSale: false,
  },
  {
    id: "8",
    name: "Denim Jeans",
    description: "Classic fit denim jeans with stretch comfort",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500",
    category: "Clothing",
    stock: 90,
    rating: 4.4,
    isNew: false,
    onSale: true,
  },
  {
    id: "9",
    name: "Cookbook Collection",
    description: "Set of 3 bestselling cookbooks for home chefs",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500",
    category: "Books",
    stock: 40,
    rating: 4.8,
    isNew: false,
    onSale: false,
  },
  {
    id: "10",
    name: "Backpack",
    description: "Durable laptop backpack with USB charging port",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
    category: "Sports",
    stock: 70,
    rating: 4.5,
    isNew: true,
    onSale: false,
  },
  {
    id: "11",
    name: "Blender",
    description: "High-speed blender for smoothies and soups",
    price: 119.99,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=500",
    category: "Home & Kitchen",
    stock: 35,
    rating: 4.6,
    isNew: false,
    onSale: true,
  },
  {
    id: "12",
    name: "Sunglasses",
    description: "UV protection polarized sunglasses",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500",
    category: "Clothing",
    stock: 100,
    rating: 4.3,
    isNew: false,
    onSale: false,
  },
  {
    id: "13",
    name: "Gaming Mouse",
    description: "RGB gaming mouse with programmable buttons",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500",
    category: "Electronics",
    stock: 65,
    rating: 4.7,
    isNew: true,
    onSale: false,
  },
  {
    id: "14",
    name: "Cutting Board Set",
    description: "Bamboo cutting board set with juice groove",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1594756202469-9ff9799b2e4e?w=500",
    category: "Home & Kitchen",
    stock: 50,
    rating: 4.5,
    isNew: false,
    onSale: false,
  },
  {
    id: "15",
    name: "Winter Jacket",
    description: "Insulated waterproof winter jacket",
    price: 159.99,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
    category: "Clothing",
    stock: 45,
    rating: 4.6,
    isNew: true,
    onSale: true,
  },
];
